<a href="https://colab.research.google.com/github/Mohdd-Afaan/data-science-master-2.0/blob/main/Feature_Engineering_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when you
might choose one over the other.

Ans: Ordinal Encoding and Label Encoding are both techniques used to convert categorical variables into numerical format, but they differ in how they assign numerical values to categories.

Ordinal Encoding:

In Ordinal Encoding, each unique category is mapped to an integer value based on the order or rank of the categories.
The numerical values assigned have an inherent order or hierarchy.
It is suitable for categorical variables where there is a natural ranking or order among the categories.
Example:
Consider a categorical variable "Education Level" with categories "High School", "Bachelor's Degree", "Master's Degree", and "Ph.D.". Ordinal Encoding could map these categories as follows:

High School: 1
Bachelor's Degree: 2
Master's Degree: 3
Ph.D. : 4
Label Encoding:

In Label Encoding, each unique category is assigned a unique integer value, typically starting from 0 or 1 and incrementing for each new category.
There is no inherent order or hierarchy in the numerical values assigned.
It is suitable for categorical variables where there is no natural ranking or order among the categories.
Example:
Using the same "Education Level" variable, Label Encoding could map the categories as follows:

High School: 0
Bachelor's Degree: 1
Master's Degree: 2
Ph.D. : 3
When to choose one over the other:

Use Ordinal Encoding when there is a clear order or ranking among the categories. For example, when encoding education levels or grades.
Use Label Encoding when there is no inherent order among the categories or when preserving the order may introduce unintended relationships between categories. For example, when encoding categorical variables like city names or types of cars.

Q2. Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it in
a machine learning project.

Ans:
Target Guided Ordinal Encoding is a feature engineering technique used for encoding categorical variables based on their relationship with the target variable in a supervised machine learning task. It assigns ordinal labels to categories based on the target variable's mean or median value for each category.

Here's how Target Guided Ordinal Encoding works:

Calculate the Mean/Median Target Variable for Each Category:

For each category in the categorical variable, calculate the mean or median of the target variable within that category.
Order Categories Based on Mean/Median Target Variable:

Order the categories based on their corresponding mean or median target variable values, from the lowest to the highest.
Assign Ordinal Labels:

Assign ordinal labels to the categories based on their order. For example, the category with the lowest mean or median target variable value may be assigned a label of 1, the next category a label of 2, and so on.
Replace Categories with Ordinal Labels:

Replace the original categorical variable with the assigned ordinal labels.
Example Usage:

Consider a dataset for predicting customer churn in a telecommunications company. One of the features is "Subscription Plan," which includes categories like "Basic," "Standard," and "Premium."

You want to encode this categorical variable into ordinal labels based on the average churn rate for each subscription plan.
Using Target Guided Ordinal Encoding, you calculate the average churn rate for each subscription plan:
Basic: 20% churn rate
Standard: 15% churn rate
Premium: 5% churn rate
Based on the churn rates, you assign ordinal labels:
Basic: 3 (highest churn rate)
Standard: 2 (medium churn rate)
Premium: 1 (lowest churn rate)
Replace the original "Subscription Plan" feature with the assigned ordinal labels in your dataset.

Q3. Define covariance and explain why it is important in statistical analysis. How is covariance calculated?

Ans: Covariance is a statistical measure that quantifies the degree to which two random variables change together. In other words, it measures the relationship between two variables. If the variables tend to increase or decrease together, the covariance is positive. If one variable tends to increase while the other decreases, the covariance is negative. A covariance of zero indicates that there is no linear relationship between the variables.

Covariance is important in statistical analysis for several reasons:

Relationship Assessment: Covariance helps assess the direction of the relationship between two variables. A positive covariance indicates a positive relationship, while a negative covariance indicates a negative relationship.

Strength of Relationship: The magnitude of the covariance provides information about the strength of the relationship between variables. Larger covariance values indicate a stronger relationship, while smaller values indicate a weaker relationship.

Portfolio Management: In finance, covariance is used to measure the co-movement of assets within a portfolio. It helps investors assess the diversification benefits of adding new assets to their portfolio.

covariance can be calculated using the following formula:
cov(X,Y)= (XiYi/n)-(means of variables X and Y)

It's important to note that covariance is influenced by the scale of the variables. Therefore, it is often normalized to produce a correlation coefficient, which is a standardized measure of linear association that ranges from -1 to 1.

Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium,
large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library.
Show your code and explain the output.

In [ ]:
import pandas as pd
df = pd.DataFrame({'Color':['red','green','blue'],'Size':['small','medium','large'],'Material':['wood','metal','plastic']})
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['Color_Encoded'] = encoder.fit_transform(df['Color'])
df

Color    Size Material  Color_Encoded
0    red   small     wood              2
1  green  medium    metal              1
2   blue   large  plastic              0

Explanation:

We first create a sample dataset data containing the categorical variables Color, Size, and Material.

We convert this dictionary to a pandas DataFrame df.

We initialize a LabelEncoder.

We apply label encoding on color feature because the remaining features size (have inherit order eg: 1ft, 2ft, 3ft etc) and material(have inherit order interms of strength)

We append the encoded column to the original DataFrame.

Finally, we print the resulting DataFrame with the encoded column.


Q5. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education
level. Interpret the results.

In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'Age':[24,25,26,27,29],'Income': [50000, 60000, 75000, 80000, 90000],'Education_Level': [12, 14, 16, 18, 20]})

cov_matrix = df.cov()

cov_matrix

Age       Income  Education_Level
Age                  3.7      29750.0              6.0
Income           29750.0  255000000.0          50000.0
Education_Level      6.0      50000.0             10.0

Interpretation of the results:

The covariance matrix is a square matrix where the diagonal elements represent the variances of each variable, and the off-diagonal elements represent the covariances between pairs of variables.
For example, the covariance between Age and Income is 29750.0, indicating a positive relationship between Age and Income. This means that as Age increases, Income tends to increase as well.
Similarly, the covariance between Age and Education_Level is 6.0, indicating a positive relationship between Age and Education_Level. However, the magnitude of this covariance is much smaller compared to the covariance between Age and Income, suggesting a weaker relationship.
The covariance between Income and Education_Level is 50000.0, indicating a positive relationship between Income and Education_Level. This means that as Income increases, Education_Level tends to increase as well.
It's important to note that the scale of the variables affects the magnitude of the covariance. Therefore, the covariance values themselves may not be easily interpretable without considering the scales of the variables.

Q6. You are working on a machine learning project with a dataset containing several categorical
variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD),
and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for
each variable, and why?

Ans: For each categorical variable in the dataset, the choice of encoding method depends on various factors such as the nature of the variable, the number of categories, and the machine learning algorithm being used. Here's a recommendation for each variable:

Gender (Binary Variable: Male/Female):
For binary categorical variables like "Gender," you can use binary encoding or one-hot encoding. Since there are only two categories (Male/Female), either method would be appropriate. However, binary encoding would be more memory-efficient as it uses fewer dimensions than one-hot encoding.

Education Level (Ordinal Variable: High School, Bachelor's, Master's, PhD):
For ordinal categorical variables like "Education Level," where there is a clear order or hierarchy among the categories, you can use ordinal encoding. In ordinal encoding, each category is assigned an integer value based on its order. This method preserves the ordinal relationship between categories, which might be important for some machine learning algorithms.

Employment Status (Nominal Variable: Unemployed, Part-Time, Full-Time):
For nominal categorical variables like "Employment Status," where there is no inherent order or hierarchy among the categories, one-hot encoding is typically used. One-hot encoding creates binary columns for each category, indicating its presence or absence in each observation. This method prevents the model from assuming any ordinal relationship between categories.

Q7. You are analyzing a dataset with two continuous variables, "Temperature" and "Humidity", and two
categorical variables, "Weather Condition" (Sunny/Cloudy/Rainy) and "Wind Direction" (North/South/
East/West). Calculate the covariance between each pair of variables and interpret the results.

In [3]:
import pandas as pd

data = {
    'Temperature': [25, 28, 22, 24, 27],
    'Humidity': [60, 55, 70, 65, 75],
    'Weather Condition': ['Sunny', 'Cloudy', 'Rainy', 'Cloudy', 'Rainy'],
    'Wind Direction': ['North', 'South', 'East', 'West', 'North']
}

df = pd.DataFrame(data)

covariance_matrix = df.cov()

print(covariance_matrix)

             Temperature  Humidity
Temperature         5.70     -6.25
Humidity           -6.25     62.50


<ipython-input-3-d3a0e042b999>:12: FutureWarning: The default value of numeric_only in DataFrame.cov is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  covariance_matrix = df.cov()


Interpreting the covariance matrix:

The diagonal elements of the covariance matrix represent the variances of individual variables. For example, the covariance of "Temperature" with itself represents its variance.
Off-diagonal elements represent the covariances between pairs of variables. For example, the covariance between "Temperature" and "Humidity" is captured in the element corresponding to those variables.
Interpretation:

Positive covariance: If the covariance between two variables is positive, it indicates that they tend to increase or decrease together. For example, if temperature increases, humidity might also increase.
Negative covariance: If the covariance between two variables is negative, it indicates that they tend to vary in opposite directions. For example, if temperature increases, humidity might decrease.
Covariance near zero: If the covariance between two variables is close to zero, it indicates that there is little to no linear relationship between them.